import { loadArchiveQuestions } from './match-data.js';
import { iconicQuestions } from './iconic-moments.js';

const bank=[
{cat:'WORLD CUP',q:'Who scored the fastest goal in FIFA World Cup history, after just 11 seconds?',a:['hakan sukur','hakan şükür'],fact:'Hakan Şükür scored after 11 seconds for Türkiye against South Korea in 2002.'},
{cat:'WORLD CUP',q:'Which country did Spain beat in the 2010 final?',a:['netherlands','holland'],fact:'Andrés Iniesta’s extra-time winner gave Spain a 1–0 win over the Netherlands.'},
{cat:'WORLD CUP',q:'Who was the first player sent off in a men’s World Cup final?',a:['pedro monzon','monzon'],fact:'Argentina’s Pedro Monzón was dismissed in the 1990 final against West Germany.'},
{cat:'WORLD CUP',q:'Which Brazilian scored the winning penalty in the 1994 World Cup final?',a:['dunga'],fact:'Dunga converted Brazil’s fourth penalty after Roberto Baggio sent Italy’s final kick over the bar.'},
{cat:'WORLD CUP',q:'Which African nation became the first to reach a World Cup quarter-final?',a:['cameroon'],fact:'Cameroon reached the quarter-finals at Italia 1990, losing to England after extra time.'},
{cat:'WORLD CUP',q:'Who scored the only goal of the 1966 World Cup final?',a:['geoff hurst','hurst'],fact:'Geoff Hurst scored a hat-trick in England’s 4–2 extra-time win; his first came in the 18th minute.'},
{cat:'WORLD CUP',q:'Which nation did North Korea upset in the 1966 quarter-finals?',a:['italy'],fact:'Pak Doo-ik’s goal eliminated Italy in Middlesbrough.'},
{cat:'WORLD CUP',q:'Who is the only goalkeeper to win the World Cup Golden Ball?',a:['oliver kahn','kahn'],fact:'Oliver Kahn won the Golden Ball at the 2002 World Cup.'},
{cat:'WORLD CUP',q:'Which country hosted the first World Cup in 1930?',a:['uruguay'],fact:'Uruguay hosted and won the inaugural tournament.'},
{cat:'WORLD CUP',q:'Which player scored five goals in one match at the 1994 World Cup?',a:['oleg salenko','salenko'],fact:'Russia’s Oleg Salenko scored five against Cameroon, a single-match record.'},
{cat:'WORLD CUP',q:'Who scored the winning penalty in the 2006 World Cup final shootout?',a:['fabio grosso','grosso'],fact:'Fabio Grosso converted Italy’s fifth penalty against France.'},
{cat:'WORLD CUP',q:'Which country did Senegal defeat in their opening match at the 2002 World Cup?',a:['france'],fact:'Senegal stunned defending champions France 1–0 in Seoul.'},
{cat:'WORLD CUP',q:'What was the name of the ball used in the 1970 World Cup?',a:['telstar'],fact:'Adidas Telstar introduced the now-iconic black-and-white panel design.'},
{cat:'WORLD CUP',q:'Which player scored the first own goal in a men’s World Cup final?',a:['mario mandzukic','mandzukic'],fact:'Mario Mandžukić headed into his own net in the 2018 final.'},
{cat:'WORLD CUP',q:'Who was the oldest goalscorer in men’s World Cup history before 2026?',a:['roger milla','milla'],fact:'Cameroon’s Roger Milla scored aged 42 against Russia in 1994.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored the first goal in the 1992–93 UEFA Champions League era?',a:['daniel amokachi','amokachi'],fact:'Daniel Amokachi scored for Club Brugge against CSKA Moscow.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club did Porto beat in the 2004 Champions League final?',a:['monaco'],fact:'José Mourinho’s Porto defeated Monaco 3–0 in Gelsenkirchen.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored Liverpool’s equaliser in the 2005 final comeback?',a:['steven gerrard','gerrard'],fact:'Steven Gerrard’s 54th-minute header began Liverpool’s comeback in Istanbul.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club became the first from outside Europe’s traditional top-five leagues to win the Champions League?',a:['porto'],fact:'Porto won the 2003–04 competition under José Mourinho.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored the winning goal in the 1999 final, after Solskjær?',a:['teddy sheringham','sheringham'],fact:'Teddy Sheringham equalised before Ole Gunnar Solskjær’s winner.'},
{cat:'CHAMPIONS LEAGUE',q:'Which team did Real Madrid beat to win La Décima?',a:['atletico madrid'],fact:'Real Madrid beat city rivals Atlético 4–1 after extra time in 2014.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored the only goal in the 2008 final before the shootout?',a:['cristiano ronaldo','ronaldo'],fact:'Cristiano Ronaldo scored for Manchester United; Frank Lampard equalised.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club did Marseille defeat in the first Champions League final?',a:['ac milan','milan'],fact:'Marseille beat AC Milan 1–0 in Munich in 1993.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored Barcelona’s opener in the 2009 final against Manchester United?',a:['samuel eto’o','samuel eto\'o','eto’o','eto\'o'],fact:'Samuel Eto’o opened the scoring in Barcelona’s 2–0 win.'},
{cat:'CHAMPIONS LEAGUE',q:'Which goalkeeper saved John Terry’s penalty in the 2008 final?',a:['edwin van der sar','van der sar'],fact:'Edwin van der Sar saved Chelsea captain John Terry’s sudden-death penalty.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club won the 1986 European Cup final on penalties against Barcelona?',a:['steaua bucharest','steaua'],fact:'Steaua București won 2–0 on penalties; Helmut Duckadam saved all four Barcelona attempts.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored the winning goal for Chelsea in the 2012 final?',a:['didier drogba','drogba'],fact:'Didier Drogba headed Chelsea level, then scored the decisive shootout penalty.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club did Nottingham Forest beat in the 1979 European Cup final?',a:['malmo','malmo ff'],fact:'Forest beat Malmö FF 1–0 in Munich, with Trevor Francis scoring.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored the overhead kick remembered from the 2018 final?',a:['gareth bale','bale'],fact:'Gareth Bale’s bicycle kick put Real Madrid ahead against Liverpool.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club did Ajax beat in the 1995 final?',a:['ac milan','milan'],fact:'Ajax beat defending champions AC Milan 1–0 through Patrick Kluivert.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Who scored the winning goal for Greece in the EURO 2004 final?',a:['angelos charisteas','charisteas'],fact:'Angelos Charisteas scored the only goal against Portugal.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Who scored the golden goal penalty that sent France into the EURO 2000 final?',a:['zinedine zidane','zidane'],fact:'Zinedine Zidane converted the extra-time penalty against Portugal.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Who scored the winning penalty for Italy in the EURO 2020 final shootout?',a:['federico bernardeschi','bernardeschi'],fact:'Bernardeschi scored Italy’s second penalty; Donnarumma saved England’s final two.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Which country did Denmark replace at EURO 1992?',a:['yugoslavia'],fact:'Denmark entered after Yugoslavia were disqualified and went on to win the tournament.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Who scored the only goal in the EURO 1996 final?',a:['oliver bierhoff','bierhoff'],fact:'Oliver Bierhoff’s golden goal gave Germany victory over Czechia.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Which player scored the famous volley in the EURO 1988 final?',a:['marco van basten','van basten'],fact:'Marco van Basten’s volley sealed the Netherlands’ 2–0 win over the Soviet Union.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Who scored the winning goal for Portugal in the EURO 2016 final?',a:['eder'],fact:'Eder scored from outside the box in extra time against France.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Which nation did Spain beat 4–0 in the EURO 2012 final?',a:['italy'],fact:'Spain became the first team to retain the EURO title, defeating Italy 4–0.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Who scored the winning goal in the EURO 2000 final?',a:['david trezeguet','trezeguet'],fact:'David Trezeguet’s golden goal gave France the title against Italy.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Which player became the youngest scorer in EURO history at EURO 2004?',a:['wayne rooney','rooney'],fact:'Wayne Rooney scored aged 18 years and 237 days against Switzerland.'},
{cat:'COPA AMÉRICA',q:'Which country hosted and won the first Copa América in 1916?',a:['argentina'],fact:'The inaugural South American Championship was held in Argentina.'},
{cat:'COPA AMÉRICA',q:'Who scored Argentina’s winning goal in the 2021 final?',a:['angel di maria','di maria'],fact:'Ángel Di María chipped Ederson to beat Brazil at the Maracanã.'},
{cat:'COPA AMÉRICA',q:'Which country did Chile defeat in the 2015 final shootout?',a:['argentina'],fact:'Chile won its first Copa América title by beating Argentina on penalties.'},
{cat:'COPA AMÉRICA',q:'Who was Uruguay’s captain when they won the 2011 Copa América?',a:['diego lugano','lugano'],fact:'Diego Lugano captained Uruguay to a 3–0 final win over Paraguay.'},
{cat:'AFCON',q:'Which nation won AFCON 2012 despite not qualifying for AFCON 2013?',a:['zambia'],fact:'Zambia beat Côte d’Ivoire on penalties in a final played in Libreville.'},
{cat:'AFCON',q:'Which goalkeeper scored the winning penalty for Côte d’Ivoire in the 2015 AFCON final?',a:['boubacar barry','barry'],fact:'Keeper Boubacar Barry scored the 11th penalty in the shootout against Ghana.'},
{cat:'AFCON',q:'Which country did Algeria beat in the 2019 AFCON final?',a:['senegal'],fact:'BAGhdad Bounedjah’s deflected strike was enough to beat Senegal 1–0.'},
{cat:'WORLD CUP',q:'Which country did Morocco defeat to become the first African World Cup semi-finalist?',a:['portugal'],fact:'Morocco beat Portugal 1–0 in the 2022 quarter-final.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club eliminated Barcelona in the 2019 semi-final after losing the first leg 3–0?',a:['liverpool'],fact:'Liverpool won the Anfield second leg 4–0.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Who scored the winning goal in the EURO 2024 final?',a:['mikel oyarzabal','oyarzabal'],fact:'Mikel Oyarzabal scored late for Spain against England.'},
{cat:'WORLD CUP',q:'Which player won the Golden Boot at the 2010 World Cup?',a:['thomas muller','thomas müller','muller','müller'],fact:'Thomas Müller won on assists after sharing five goals with four others.'},
{cat:'WORLD CUP',q:'Which country did Brazil beat in the 1958 final?',a:['sweden'],fact:'Brazil beat hosts Sweden 5–2, winning their first World Cup.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club did Bayern Munich beat in the 2013 final?',a:['borussia dortmund','dortmund'],fact:'Arjen Robben scored late to beat domestic rivals Borussia Dortmund at Wembley.'},
{cat:'WORLD CUP',q:'Who coached Italy to the 2006 World Cup title?',a:['marcello lippi','lippi'],fact:'Marcello Lippi led Italy to victory over France on penalties.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Which team did Iceland eliminate in the EURO 2016 round of 16?',a:['england'],fact:'Iceland beat England 2–1 in one of the tournament’s biggest upsets.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored the winning goal in the 2021 Champions League final?',a:['kai havertz','havertz'],fact:'Kai Havertz scored Chelsea’s winner against Manchester City.'},
{cat:'WORLD CUP',q:'Which defender scored the golden goal that eliminated Italy in 2002?',a:['ahn jung-hwan','ahn jung hwan'],fact:'Ahn Jung-hwan’s extra-time header sent South Korea through.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Which player scored a hat-trick in the EURO 2020 final?',a:['no one','nobody'],fact:'No one: the final ended 1–1 after extra time; no player scored a hat-trick.'},
{cat:'CHAMPIONS LEAGUE',q:'What was the name of the stadium where the 2005 final was played?',a:['ataturk olympic stadium','ataturk stadium','atatürk olympic stadium'],fact:'The Atatürk Olympic Stadium in Istanbul hosted the 2005 final.'},
{cat:'WORLD CUP',q:'Which nation did Uruguay beat in the 1950 decisive match at the Maracanã?',a:['brazil'],fact:'Uruguay beat Brazil 2–1 in the match often called the Maracanazo.'},
{cat:'WORLD CUP',q:'Who scored the first goal of the 2014 World Cup?',a:['marcelo'],fact:'Brazil defender Marcelo scored an own goal in the opening match against Croatia.'},
{cat:'CHAMPIONS LEAGUE',q:'Which club did Real Madrid beat in the 2022 final?',a:['liverpool'],fact:'Vinícius Júnior scored the only goal against Liverpool in Paris.'},
{cat:'WORLD CUP',q:'Who scored the golden goal in the 2002 World Cup final?',a:['there was no golden goal','no golden goal'],fact:'There was no golden goal in the final. Ronaldo scored twice in normal time for Brazil.'},
{cat:'EUROPEAN CHAMPIONSHIP',q:'Which team did Czechoslovakia beat in the EURO 1976 final?',a:['west germany','germany'],fact:'Antonín Panenka’s chipped penalty sealed the shootout win over West Germany.'},
{cat:'CHAMPIONS LEAGUE',q:'Who scored the winning goal in the 2014 final, deep into extra time?',a:['cristiano ronaldo','ronaldo'],fact:'Ronaldo’s penalty made it 4–1 after Gareth Bale, Marcelo and he added extra-time goals.'}
];
bank.push(...iconicQuestions);
window.questionBank=bank;
window.questionBankReady=loadArchiveQuestions().then(extra=>{const needed=Math.max(0,3000-bank.length);bank.push(...shuffle(extra).slice(0,needed));window.questionBank=bank;const count=$('questionPoolStatus');if(count)count.textContent=bank.length===3000?'3,000 DISTINCT QUESTIONS READY':`${bank.length} QUESTIONS READY · ARCHIVE PARTIAL`;return bank}).catch(()=>{const count=$('questionPoolStatus');if(count)count.textContent=`${bank.length} CURATED QUESTIONS · ARCHIVE UNAVAILABLE`;return bank});
const $=id=>document.getElementById(id);let round=[],index=0,score=0,streak=0,locked=false;
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function begin(){const button=$('startBtn');if(button)button.disabled=true;await window.questionBankReady;const cats=[['WORLD CUP',1],['WORLD CUP ARCHIVE',1],['CHAMPIONS LEAGUE',1],['CHAMPIONS LEAGUE ARCHIVE',1],['EUROPEAN CHAMPIONSHIP',1],['EUROPEAN CHAMPIONSHIP ARCHIVE',1],['COPA AMÉRICA',1],['AFCON',1],['ICONIC MOMENTS',3]];round=cats.flatMap(([cat,n])=>shuffle(bank.filter(q=>q.cat===cat)).slice(0,n));const chosen=new Set(round);round.push(...shuffle(bank.filter(q=>!chosen.has(q))).slice(0,15-round.length));round=shuffle(round);index=score=streak=0;show('quiz');draw();if(button)button.disabled=false}
function show(which){['intro','quiz','results'].forEach(id=>$(id).classList.toggle('hidden',id!==which))}
function draw(){locked=false;let item=round[index];$('category').textContent=item.cat;$('counter').innerHTML=`${String(index+1).padStart(2,'0')} <i>/ 15</i>`;$('streak').textContent=`${streak} STREAK`;$('score').textContent=String(score).padStart(2,'0');$('progress').style.width=`${index/15*100}%`;$('questionIndex').textContent=String(index+1).padStart(2,'0');$('question').textContent=item.q;$('answer').value='';$('answer').disabled=false;$('submitBtn').disabled=false;$('feedback').textContent='';$('feedback').className='feedback';setTimeout(()=>$('answer').focus(),80)}
function submit(){if(locked)return;let val=norm($('answer').value);if(!val){$('feedback').textContent='Put something on the board first.';$('feedback').className='feedback wrong';$('answer').focus();return}locked=true;let item=round[index],ok=item.a.some(x=>norm(x)===val);if(ok){score++;streak++;$('feedback').textContent=`ON THE MONEY. ${item.fact}`;$('feedback').className='feedback correct'}else{streak=0;$('feedback').textContent=`NOT QUITE. ${item.fact}`;$('feedback').className='feedback wrong'}$('score').textContent=String(score).padStart(2,'0');$('streak').textContent=`${streak} STREAK`;$('answer').disabled=true;$('submitBtn').disabled=true;$('progress').style.width=`${(index+1)/15*100}%`;setTimeout(()=>{index++;if(index===15)finish();else draw()},1850)}
function finish(){show('results');$('finalScore').textContent=String(score).padStart(2,'0');$('resultFill').style.width=`${score/15*100}%`;let title,copy;if(score===15){title='YOU ARE THE ARCHIVE.';copy='Flawless. Somewhere, a stadium floodlight just flickered in your honour.'}else if(score>=12){title='ABSOLUTE FOOTBALL NERD.';copy='The kind of knowledge that wins pub arguments and loses you the remote.'}else if(score>=8){title='YOU KNOW YOUR STUFF.';copy='A proper football brain. A few deep cuts still slipped through.'}else if(score>=4){title='A STUDENT OF THE GAME.';copy='The highlights are familiar. The footnotes are calling.'}else{title='THE WHISTLE IS A WAKE-UP CALL.';copy='No shame in a fresh start. The game is full of stories.'}$('resultTitle').textContent=title;$('resultCopy').textContent=copy;$('shareHint').textContent=`${score} / 15 CORRECT · ${Math.round(score/15*100)}% ACCURACY`}
$('startBtn').addEventListener('click',begin);$('replayBtn').addEventListener('click',begin);$('submitBtn').addEventListener('click',submit);$('answer').addEventListener('keydown',e=>{if(e.key==='Enter')submit()});$('themeBtn').addEventListener('click',()=>{let el=$('themeBtn').querySelector('span');el.textContent=el.textContent==='OFF'?'ON':'OFF';if(el.textContent==='ON'){try{const C=window.AudioContext||window.webkitAudioContext;if(C){const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=240;g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}}catch{}}});
